services:
  app:
    container_name: app
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    expose:
      - "9000"  # PHP-FPM будет слушать на порту 9000 внутри контейнера
    depends_on:
      - nginx

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    ports:
      - "8001:80"

  test-container:
    container_name: test-container
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html

